web

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,27 +1,26 @@
 #!/usr/bin/env bash
-# A Bash script that transfers a file from a client to a server:
-
-# Check if at least 4 arguments are passed to the script
-if [[ "$#" -lt 4 ]]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# checking for command line arguments
+if [ $# -lt 4 ]
+then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
-# Assign the arguments to variables for readability
+# assigning paramentals to variables
 
-file_path=$1
+path_to_file=$1
 ip=$2
 username=$3
-ssh_key=$4
+path_to_ssh_key=$4
 
-# Disable strict host key checking for the ssh connection
-ssh_options="-o StrictHostKeyChecking=no"
 
-# Use scp to transfer the file to the user's home directory on the remote server
-# -i option specifies the private key to use for authentication
-# $ssh_options variable sets the ssh options we need to disable strict host key checking
-# $file_path is the path to the file we want to transfer
-# $username@$ip specifies the user and IP of the remote server we want to transfer the file to
-# :~ specifies the user's home directory on the remote server
+# disabbling strict host key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-scp -i "$ssh_key" $ssh_options "$file_path" "$username@$ip":~
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+  echo "FILE TRANSFER FAILED"
+fi
